"use client"

import Link from "next/link"
import { motion } from "framer-motion"
import { Button } from "@/components/ui/button"
import { Wallet, ArrowLeft } from "lucide-react"
import { ModeToggle } from "@/components/mode-toggle"

const C = { deep: "#015C92", primary: "#2D82B5" } as const

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: (i = 0) => ({
    opacity: 1, y: 0,
    transition: { duration: 0.5, delay: i * 0.08, ease: [0.25, 0.4, 0.25, 1] as [number, number, number, number] },
  }),
}

const sections = [
  {
    title: "Acceptance of Terms",
    body: "By accessing or using MASARI-AI, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.",
  },
  {
    title: "Use of the Service",
    body: "MASARI-AI is a personal finance management tool. You may use it only for lawful purposes and in accordance with these terms. You are responsible for maintaining the security of your account credentials.",
  },
  {
    title: "User Data",
    body: "You retain full ownership of all financial data you enter. We do not claim any rights over your data. You are responsible for the accuracy of the information you provide.",
  },
  {
    title: "AI-Generated Content",
    body: "Financial insights and recommendations generated by our AI are for informational purposes only and do not constitute financial advice. Always consult a qualified financial advisor for important decisions.",
  },
  {
    title: "Service Availability",
    body: "We strive to keep MASARI-AI available at all times but cannot guarantee uninterrupted access. We reserve the right to modify or discontinue the service with reasonable notice.",
  },
  {
    title: "Limitation of Liability",
    body: "MASARI-AI is provided \"as is\" without warranties of any kind. We are not liable for any financial decisions made based on information provided by the service.",
  },
  {
    title: "Changes to Terms",
    body: "We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the new terms.",
  },
  {
    title: "Contact",
    body: "For questions about these terms, please reach out via our Contact page.",
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f8fafc] dark:bg-[#020617] text-slate-900 dark:text-white transition-colors duration-300">
      <header className="flex items-center justify-between px-6 md:px-12 h-16 border-b border-slate-200 dark:border-slate-800">
        <Link href="/" className="flex items-center gap-2 font-bold text-base">
          <div className="flex h-8 w-8 items-center justify-center rounded-xl"
            style={{ background: `linear-gradient(135deg,${C.deep},${C.primary})` }}>
            <Wallet className="h-4 w-4 text-white" />
          </div>
          <span style={{ color: C.primary }}>MA<span style={{ color: C.deep }}>$</span>ARI-AI</span>
        </Link>
        <div className="flex items-center gap-3">
          <ModeToggle />
          <Button variant="ghost" size="sm" asChild>
            <Link href="/" className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
              <ArrowLeft className="h-4 w-4" /> Back
            </Link>
          </Button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <motion.div variants={fadeUp} initial="hidden" animate="show" className="mb-12">
          <p className="text-sm font-semibold uppercase tracking-widest mb-3" style={{ color: C.primary }}>Legal</p>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
          <p className="text-slate-500 dark:text-slate-400">Last updated: April 2026</p>
        </motion.div>

        <div className="space-y-8">
          {sections.map((s, i) => (
            <motion.div key={s.title} variants={fadeUp} initial="hidden" animate="show" custom={i}>
              <h2 className="text-xl font-semibold mb-2" style={{ color: C.primary }}>{s.title}</h2>
              <p className="text-slate-600 dark:text-slate-400 leading-relaxed">{s.body}</p>
            </motion.div>
          ))}
        </div>
      </main>
    </div>
  )
}
